var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,h,g){d instanceof String&&(d=String(d));for(var k=d.length,l=0;l<k;l++){var u=d[l];if(h.call(g,u,l,d))return{i:l,v:u}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,h,g){d!=Array.prototype&&d!=Object.prototype&&(d[h]=g.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,h,g,k){if(h){g=$jscomp.global;d=d.split(".");for(k=0;k<d.length-1;k++){var l=d[k];l in g||(g[l]={});g=g[l]}d=d[d.length-1];k=g[d];h=h(k);h!=k&&null!=h&&$jscomp.defineProperty(g,d,{configurable:!0,writable:!0,value:h})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(d,g){return $jscomp.findInternal(this,d,g).v}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var d=0;return function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+d++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(d){var h=0;return $jscomp.iteratorPrototype(function(){return h<d.length?{done:!1,value:d[h++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};$jscomp.iteratorFromArray=function(d,h){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var g=0,k={next:function(){if(g<d.length){var l=g++;return{value:h(l,d[l]),done:!1}}k.next=function(){return{done:!0,value:void 0}};return k.next()}};k[Symbol.iterator]=function(){return k};return k};
$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
window.Kmgtm=window.Kmgtm||function(d){function h(){var a={},b=!1,c=0,d=arguments.length;"[object Boolean]"===Object.prototype.toString.call(arguments[0])&&(b=arguments[0],c++);for(;c<d;c++){var e=void 0,f=arguments[c];for(e in f)Object.prototype.hasOwnProperty.call(f,e)&&(b&&"[object Object]"===Object.prototype.toString.call(f[e])?a[e]=h(!0,a[e],f[e]):a[e]=f[e])}return a}function g(a){w("kmgtmdebug")&&window.console&&console.log(a)}function k(){var a=$(this).closest(e.settings.product),b=a.find('img[src*="/wa-data/public/shop/products/"]');
b=b.length?b.attr("src").match(/\/wa-data\/public\/shop\/products\/(\d+)\//):!1;return b=!b&&a.find('input[name="product_id"]').length?a.find('input[name="product_id"]').val():b.length&&2===b.length?b[1]:""}function l(a){var b=$(this),c=b.attr("href"),d=$(e.settings.product),f=k.call(this),l=0,z=x();try{d.each(function(){var a=$(this),b=!1;l++;a.find("a").each(function(){if($(this).attr("href")===c)return b=!0,!1});if(b)return!1});var A=h(!0,{url:c,kmid:f,id:f,name:b.attr("title"),category:z,position:l?
l:""},K(f)),y=n(A);F||(B("kmgtmproductlist"),F=!0);L("kmgtmproductlist",y,c);var r=!(a.ctrlKey||"auxclick"===a.type||"_blank"===b.attr("target"));r&&e.settings.quicklook&&$(a.target).closest(e.settings.quicklook).length&&(r=!1);e.settings.default_ua_exist&&e.settings.ua_ee&&t.onProductClick(A,r);e.settings.use_gtm&&e.settings.gtm_ee&&v.onProductClick(A,r)}catch(J){g(J)}}function u(){var a=function(a){a=a.data;try{e.settings.default_ua_exist&&e.settings.ua_ee&&t.onProductAddRemoveToCart(a),e.settings.use_gtm&&
e.settings.gtm_ee&&v.onProductAddRemoveToCart(a)}catch(m){g(m)}},b=function(a,b,d){a=a.data;"remove"!==a.action&&(f.kmgtmCartQ[b]=d);try{e.settings.default_ua_exist&&e.settings.ua_ee&&t.onProductAddRemoveToCart(a),e.settings.use_gtm&&e.settings.gtm_ee&&v.onProductAddRemoveToCart(a)}catch(p){g(p)}},c=function(a){var b=a.data.products;a=a.data.order;try{e.settings.ua_ee&&(t.addCartProducts(b),t.addAddTransaction(a,!0)),e.settings.use_gtm&&e.settings.gtm_ee&&v.addAddTransaction(a,b,"purchase1click")}catch(M){g(M)}},
d=function(a,b){return(a=a.match(new RegExp(b+"=(\\d+)")))&&2===a.length&&void 0!==a[1]?parseInt(a[1]):!1},h={onCartSaveDelete:function(a,c){var m=d(a.data,"id"),p=parseInt(c.data.q);c="delete/"===a.url?1:0;p=p||d(a.data,"quantity");p=c?f.kmgtmCartQ[m]:p;a=void 0!==f.kmgtmCartQ[m]?f.kmgtmCartQ[m]:0;m&&p&&$.post(e.url,{item_id:m,quantity:p,quantity_old:a,delete:c},function(a){b(a,m,p)},"json")},onCartAdd:function(b,c){if(void 0!==c.status&&"ok"===c.status){var m=d(b.data,"product_id"),p=d(b.data,"sku_id");
b=d(b.data,"quantity")||1;(c=c.data.item_id||null)&&(f.kmgtmCartQ[c]=b);m&&$.post(e.url,{product_id:m,sku_id:p,quantity:b},a,"json")}}},k={recalculate:function(a,c){for(var d in c.data.order.items){var m=c.data.order.items[d];a=parseInt(m.product_id);var g=parseInt(m.sku_id),C=parseInt(m.quantity);m=void 0!==f.kmgtmCartQ[g]?f.kmgtmCartQ[g]:0;C!=m&&$.post(e.url,{sku_id:g,product_id:a,quantity:C,quantity_old:m},function(a){b(a,g,C)},"json")}},order:function(a,b){a=b.data.html?$(b.data.html):$(".instantorder-content");
b=a.find("p strong");var d="";b.length?d=b.text():(b=a.find("[data-kmgtm-order]"),b.length&&(d=b.data("kmgtm-order")));d?$.post(e.url_order,{order_id:d},c,"json"):g({"instantorder order":"no order id set"})},open:function(b,c){f.kmgtmCartQ={};"cart=1"!=b.data?(c=d(b.data,"product_id"),b=d(b.data,"sku_id"),c&&(f.kmgtmCartQ[b]=1,$.post(e.url,{product_id:c,sku_id:b},a,"json"))):$(c).find("[data-id]").each(function(){var a=$(this),b=a.data("id"),c=parseInt(a.find('[name="items['+b+'][sku_id]"]').val());
f.kmgtmCartQ[c]=parseInt(a.find('[name="items['+b+'][quantity]"]').val())})}},z={order:function(a,b){"ok"!==b.status?g({"quickorder order":"order error",data:b}):(a=parseInt(b.data.params.order_id))?$.post(e.url_order,{order_id:a},c,"json"):g({"quickorder order":"no order id",data:b})}},n=0,y=0,r={order:function(a,b){"ok"!==b.status?g({"quickorder2 order":"order error",data:b}):b.data.html&&(a=$("<div>"+b.data.html+"</div>").find("[data-kmgtm-quickorder]"))&&((a=a.data("kmgtm-quickorder"))&&!y?(n=
a,$.post(e.url_order,{order_id:a},c,"json")):g({"quickorder2 order":"no order id",data:b}))},order2:function(a,b){b&&!n?(y=b,$.post(e.url_order,{order_id:b},c,"json")):g({"quickorder2 order":"no order id",data:b})}},q={order:function(a,b){(a=$(b).find("[data-order-id]").data("order-id"))?$.post(e.url_order,{order_id:a},c,"json"):g({"storequickorder order":"no order id",data:b})}},u={order:function(a,b){b.orderId?$.post(e.url_order,{order_id:b.orderId},c,"json"):g({"bistrozakaz order":"no data",data:b})}},
w={onCartSaveDelete:function(a,b){h.onCartSaveDelete(a,b)}},x=function(){var a=function(a){var c={},d=function(a){$.post(e.url,a,function(c){b(c,a.item_id,a.quantity)},"json")};$.each(a,function(a,b){c[a]=!0;void 0!==f.kmgtmCartQ[a]?b.quantity!=f.kmgtmCartQ[a]&&d({item_id:a,quantity:b.quantity,quantity_old:f.kmgtmCartQ[a]}):d({item_id:a,quantity:b.quantity,quantity_old:0})});Object.keys(a).length<Object.keys(f.kmgtmCartQ).length&&$.each(f.kmgtmCartQ,function(a,b){void 0===c[a]&&void 0!==f.checkout2.items[a]&&
(d({item_id:a,sku_id:f.checkout2.items[a].sku_id,quantity:b,quantity_old:b,delete:1}),delete f.kmgtmCartQ[a])})};$(document).on("wa_order_cart_ready",function(a,b){$.each(b.getCartData().items,function(a,b){f.checkout2.items[b.id]=b})}).on("wa_order_cart_changed",function(b,c){a(c.cart.items);f.checkout2.items=c.cart.items}).on("wa_order_form_shipping_changed",function(a,b){b.shipping.selected_variant_id&&f.checkout2.order.shipping!=b.shipping.selected_variant_id&&$.post(e.url_checkout_step+"/shipping",
{checkout_version:e.checkout_version,checkout_step_data:{checkout_step_n:2,checkout_step_name:"shipping",checkout_step_option:b.shipping.selected_variant_id}},function(a){"ok"===a.status&&$("body").append(a.data)});f.checkout2.order.shipping=b.shipping.selected_variant_id}).on("wa_order_form_payment_changed",function(a,b){if(b.payment.selected_method_id&&f.checkout2.order.payment!=b.payment.selected_method_id){try{var c=b.payment.methods[b.payment.selected_method_id].name}catch(P){}$.post(e.url_checkout_step+
"/payment",{checkout_version:e.checkout_version,checkout_step_data:{checkout_step_n:3,checkout_step_name:"payment",checkout_step_option:c||""}},function(a){"ok"===a.status&&$("body").append(a.data)})}f.checkout2.order.payment=b.payment.selected_method_id}).one("wa_order_form_auth_changed",function(a,b){$.post(e.url_checkout_step+"/contactinfo",{checkout_version:e.checkout_version,checkout_step_data:{checkout_step_n:1,checkout_step_name:"contactinfo",checkout_step_option:""}},function(a){"ok"===a.status&&
$("body").append(a.data)})})};$(document).ready(function(){var a=$("body");if(e.settings&&e.settings.productclick&&(a.off("*.kmgtm",e.settings.productclick).on("click.kmgtm auxclick.kmgtm",e.settings.productclick,function(a){l.call(this,a)}),e.settings.quicklook))a.off("*.kmgtm",e.settings.quicklook).on("click.kmgtm",e.settings.quicklook,function(a){l.call(this,a)});$('input[name^="quantity["]').each(function(){var a=$(this),b=parseInt(a.attr("name").match(/quantity\[(\d+)\]/)[1]);f.kmgtmCartQ[b]=
parseInt(a.val())});$(document).ajaxSuccess(function(a,b,c,d){try{if(void 0!==c)if(/\/cart\//.test(window.location.pathname)&&("save/"===c.url||"delete/"===c.url)||"/cart/save/"===c.url||"/cart/delete/"===c.url)h.onCartSaveDelete(c,d);else if(/\/cart\/add\//.test(c.url))h.onCartAdd(c,d);else if(/\/instantorder\/recalculate\//.test(c.url)&&d.data.order.items)k.recalculate(c,d);else if(/\/instantorder\/order\//.test(c.url))k.order(c,d);else if(/\/instantorder\//.test(c.url))k.open(c,d);else if(/\/sendQuickorder\//.test(c.url))z.order(c,
d);else if(/\/quickorder\/send\//.test(c.url))r.order(c,d);else if(/\/storequickorder\/order\//.test(c.url)||/\/storequickorder\/cart_order\//.test(c.url))q.order(c,d);else if(/\/onestep\/save\//.test(c.url))w.onCartSaveDelete(c,d)}catch(N){g(N)}});$(document).on("quickorder-submit",".quickorder-form",function(a,b){r.order2(a,b)});$(document).on("ok.bistrozakaz.order","#bistrozakaz-wrap",function(a,b){"ok"===b.status&&u.order(a,b.data)});e.settings.categoryname&&$(e.settings.categoryname)});2==e.checkout_version&&
x()}function D(a){try{var b=window[a];b.setItem("__storage_test__","__storage_test__");b.removeItem("__storage_test__");return!0}catch(c){return c instanceof DOMException&&(22===c.code||1014===c.code||"QuotaExceededError"===c.name||"NS_ERROR_DOM_QUOTA_REACHED"===c.name)&&0!==b.length}}function L(a,b,c){if(D("localStorage")){var d=sessionStorage.getItem(a)&&JSON.parse(sessionStorage.getItem(a))||{},e={};e[c]=b;b=h(d,e);sessionStorage.setItem(a,JSON.stringify(b))}else c=c||"/",document.cookie=a+"="+
b+";path="+c,g("_cookie "+a+":"+b+":"+c)}function B(a){$(window).on("unload",function(){D("localStorage")?(sessionStorage.removeItem(a),g("_removeLocalStorage "+a)):(document.cookie=a+"=;path=/;expires="+(new Date(0)).toUTCString(),g("_removeCookie "+a))})}function w(a){return(a=document.cookie.match(new RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):void 0}function x(){var a;return window.jQuery&&(a=$(e.settings.categoryname))?(1<a.length&&
(a=a[0]),$(a).text().trim()):""}function n(a){if(f.list)return f.list;var b,c;(b=x())?f.list=b:a&&a.list?f.list=a.list:a&&(c=E(a))&&(b=c.data("kmgtmproductlist"))?f.list=b:(D("sessionStorage")?(b=window.location.pathname,b=(c=JSON.parse(sessionStorage.getItem("kmgtmproductlist")))&&void 0!==c[b]?c[b]:void 0):b=w("kmgtmproductlist"),b?f.list=b:a&&a.category&&(f.list=a.category));return f.list}function E(a){var b=parseInt(a.kmid),c=function(a){a=a.closest(e.settings.product);if(a.length){var b=x();
b&&a.data("kmgtmproductlist",b)}else a=!1;return a};if(b){var d=$('input[name="product_id"][type="hidden"][value="'+b+'"]');if(d.length)return c(d);b=$('img[src*="/'+b+'/images/"]');if(b.length)return c(b)}a=$('[itemprop="name"]:contains(\''+a.name+"')");return a.length?c(a):!1}function K(a){if(f.productImpressions.length)for(var b=0,c=f.productImpressions.length;b<c;b++)if(f.productImpressions[b].id==a)return f.productImpressions[b];return!1}function G(a,b){a.forEach(function(a){a.kmid&&a.list&&
(a=E(a))&&a.data(b)})}function O(){g("hacking ga");d.GoogleAnalyticsObject="ga";d.ga=d.ga||function(){if(!d.ga.q&&arguments[0]&&"create"!==arguments[0])(d.ga["kmq"+q]=d.ga["kmq"+q]||[]).push(arguments),g(d.ga["kmq"+q]);else{if(arguments[0]&&"create"===arguments[0])for((d.ga.q=d.ga.q||[]).push(arguments);d.ga["kmq"+q]&&d.ga["kmq"+q].length;)(d.ga.q=d.ga.q||[]).push(d.ga["kmq"+q].pop());else(d.ga.q=d.ga.q||[]).push(arguments);g(d.ga.q)}}}function H(a){var b=this;setTimeout(function(){window.jQuery?
I||(a.call(b),I=!0):H(a)},200)}var f={productImpressions:[],list:"",cartProducts:[],currentProduct:!1,kmgtmCartQ:{},checkout2:{items:{},order:{shipping:"",payment:"",contactinfo:"",confirmation:"",custom:""}}},e={},q,I=!1,F=!1,v={all_impressions:[],pushData:function(a){window.KmgtmBeforePush&&(a=window.KmgtmBeforePush(a));window[e.settings.datalayer_name].push(a);g({"kmgtmGTM push data":a})},eventEcommerceSend:function(a,b){var c="kmEcommerce"+(b?"."+b:"");b={kmEventAction:b?b:"send"};b=h(!0,b,a);
this.eventSend(c,b)},eventSend:function(a,b){b=b||{};a={event:a};a=h(!0,a,b);this.pushData(a)},onProductClick:function(a,b){var c={actionField:{list:n(a)},products:[a]};this.eventEcommerceSend({ecommerce:{click:c},kmNonInteraction:!1,eventCallback:function(){b&&(document.location=a.url)}},"productClick");this.pushData({"kmgtm.productClick":c})},_impressions:function(a){a={currencyCode:e.settings.currency_code,impressions:a};this.eventEcommerceSend({ecommerce:a},"impression");this.all_impressions=
this.all_impressions.concat(a.impressions);this.pushData({"kmgtm.impressions":{currencyCode:e.settings.currency_code,impressions:this.all_impressions}})},addImpressions:function(a){f.productImpressions=a;this._impressions(f.productImpressions)},addProductImpressions:function(a){f.productImpressions=a;var b=this;$(function(){G(f.productImpressions,{kmgtmproductlist:n(f.productImpressions.length?f.productImpressions[0]:!1)});b._impressions(f.productImpressions)})},productView:function(a){var b=n(a);
f.currentProduct=a;a={actionField:{list:b},products:[a]};this.eventEcommerceSend({ecommerce:{detail:a}},"productView");this.pushData({"kmgtm.productView":a});B("kmgtmproductlist")},onProductAddRemoveToCart:function(a){var b=n(a),c={ecommerce:{currencyCode:e.settings.currency_code}},d="add"===a.action?"addToCart":"removeFromCart";c.ecommerce[a.action]={actionField:{list:b},products:[a],kmNonInteraction:!1};"add"===a.action?this.pushData({"kmgtm.addToCart":c.ecommerce[a.action]}):this.pushData({"kmgtm.removeFromCart":c.ecommerce[a.action]});
this.eventEcommerceSend(c,d)},addAddTransaction:function(a,b,c){a={actionField:a,products:b};this.eventEcommerceSend({ecommerce:{currencyCode:e.settings.currency_code,purchase:a}},c||"purchase");this.pushData({"kmgtm.transaction":a})},addCheckoutStep:function(a,b){var c=$('[data-step-id="'+a.name+'"]').closest("form");c=c.length?c:$("#wa-step-"+a.name+"-section form");c.find("em.errormsg").length||(a={kmEventAction:a.name,ecommerceStep:a.name,ecommerce:{currencyCode:e.settings.currency_code,checkout:{actionField:{step:a.n,
option:void 0!==a.option&&a.option.length?a.option:c.find('input[name="'+a.name+'_id"]:checked').closest("label").text().trim()},products:b}}},this.pushData({"kmgtm.checkoutstep":a}),this.eventEcommerceSend(a,"checkout"))},sendOneStepCheckoutStep:function(a,b,c,d){this.eventEcommerceSend({kmEventAction:b,ecommerceStep:b,ecommerce:{currencyCode:e.settings.currency_code,checkout:{actionField:{step:a,option:c},products:d}}},"checkout");g({kmgtmGTM:{one_step_checkout:[a,b,c,d]}})}},t={ecPluginAdded:!1,
ecPlugin:function(){this.ecPluginAdded||(ga("require","ec"),this.ecPluginAdded=!0)},eventEcommerceSend:function(a,b){a=a||{};a=h(!0,{kmEventCategory:"kmEcommerce"+(b?"."+b:""),kmEventAction:b?b:"send",kmEventLabel:"",kmEventValue:"",kmFieldsObject:{nonInteraction:!0}},a);a.kmEventValue?ga("send","event",a.kmEventCategory,a.kmEventAction,a.kmEventLabel,a.kmEventValue,a.kmFieldsObject):ga("send","event",a.kmEventCategory,a.kmEventAction,a.kmEventLabel,a.kmFieldsObject);g({kmgtmGA:a})},sendEc:function(a,
b,c){c?(ga(a,b,c),g({kmgtmGA:[a,b,c]})):(ga(a,b),g({kmgtmGA:[a,b]}))},_impressions:function(a){var b=this;a.forEach(function(a){b.sendEc("ec:addImpression",a)});this.eventEcommerceSend({},"impression")},addImpressions:function(a){f.productImpressions=a;this._impressions(f.productImpressions)},addProductImpressions:function(a){f.productImpressions=a;var b=this;$(function(){G(f.productImpressions,{kmgtmproductlist:f.productImpressions[0].list});b._impressions(f.productImpressions)})},productView:function(a){var b=
n(a);f.currentProduct=a;this.sendEc("ec:addProduct",a);this.sendEc("ec:setAction","detail",{list:b});this.eventEcommerceSend({},"productView");B("kmgtmproductlist")},onProductClick:function(a,b){var c=n(a);this.sendEc("ec:addProduct",a);this.sendEc("ec:setAction","click",{list:c});this.eventEcommerceSend({kmFieldsObject:{nonInteraction:!1,hitCallback:function(){b&&(document.location=a.url)}}},"productClick");g("!!! productClick")},onProductAddRemoveToCart:function(a){var b=n(a);this.sendEc("ec:addProduct",
a);this.sendEc("ec:setAction","add"===a.action?"add":"remove",{list:b});this.eventEcommerceSend({kmFieldsObject:{nonInteraction:!1}},"add"===a.action?"addToCart":"removeFromCart")},deleteOldGaEcommerceData:function(){if(void 0!==ga&&void 0!==ga.q)for(var a=0;a<ga.q.length;a++)0<ga.q[a].length&&(/ecommerce:/.test(ga.q[a][0])||2<ga.q[a].length&&"require"===ga.q[a][0]&&"ecommerce"===ga.q[a][1]&&"ecommerce.js"===ga.q[a][2])&&delete ga.q[a]},addAddTransaction:function(a,b){b=b?"purchase1click":"purchase";
this.sendEc("ec:setAction","purchase",a);this.eventEcommerceSend({},b);f.cartProducts=[]},addCartProducts:function(a){var b=this;f.cartProducts=a||f.cartProducts;f.cartProducts.forEach(function(a){b.sendEc("ec:addProduct",a)})},addCheckoutStep:function(a,b){b=$('[data-step-id="'+a.name+'"]').closest("form");b=b.length?b:$("#wa-step-"+a.name+"-section form");b.find("em.errormsg").length||(this.sendEc("ec:setAction","checkout",{step:a.n,option:void 0!==a.option&&a.option.length?a.option:b.find('input[name="'+
a.name+'_id"]:checked').closest("label").text().trim()}),this.eventEcommerceSend({},a.name))},sendOneStepCheckoutStep:function(a,b,c){this.addCartProducts();this.sendEc("ec:setAction","checkout",{step:a,option:c});this.eventEcommerceSend({},b);g({kmgtmGA:{one_step_checkout:[a,b,c]}})},setDimension:function(a,b){ga("set","dimension"+a,b)},remarketingPluginAdded:!1,remarketingPlugin:function(){this.remarketingPluginAdded||(ga("require","displayfeatures"),this.remarketingPluginAdded=!0)}};return{o:{},
uuid:null,GTM:v,GA:t,oneCheckoutInit:function(a){a=a||[];$(document).ready(function(){var b={};$(".checkout-step").each(function(){b[$(this).data("step")]=!1});var c=function(c,d){c=0;var f=$(this).closest(".checkout-step"),g=f.data("step");d=d||!1;f.find("input").off(".kmgtmgtm");for(var h in b)if(b.hasOwnProperty(h)){c++;f=$('.checkout-step[data-step="'+h+'"]');var k=f.find('input[name="'+h+'_id"]:checked').closest("label").text().trim();if(!f.find("em.errormsg").length&&(e.settings.use_gtm&&(e.settings.use_gtm&&
e.settings.gtm_ee&&v.sendOneStepCheckoutStep(c,h,k,a),e.settings.ua_ee&&t.sendOneStepCheckoutStep(c,h,k)),!d&&h===g))break}},d=function(){$("body").on("focus.kmgtmgtm",".checkout-step input",c)};$("body").on("change.kmgtm",".checkout-step :radio",function(){c.call(this);d()}).on("submit.kmgtm","form.checkout-form",function(){setTimeout(function(){c(!0)},100)});d()})},init:function(a){this.uuid=Math.random().toString(36).substr(2,9);e=this.o=a;q=this.uuid;g(e);if(2==w("kmgtmdebug"))debugger;e.settings.default_ua_exist&&
O();H(u)},findProductWrapper:E,data:f}}(window);
